name: Generate Metrics Card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Metrics Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Asachdeva001&show_icons=true&hide_title=true&hide_rank=true
          path: assets/github-metrics.svg
          token: ${{ secrets.GH_TOKEN }} # Uses your custom secret name

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-metrics.svg
          git commit -m "Update github-metrics.svg" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Links your secret for the push command
